### ISSUE TITLE
Some code running issues

### ISSUE THREAD

**Issue by BITwtz** [JWFanggit/LOTVS-CAP#4]
<img width="1132" alt="微信图片_20231211092112" src="https://github.com/JWFanggit/LOTVS-CAP/assets/153470867/084eb83e-5358-4f4e-accf-86e1c48f3d45">
I encountered the error message in the picture, and I saw that someone had encountered the same problem before, may I ask how to solve this problem?

**Comment by JWFanggit** [comment]
Hi. Here's a notation error in my code. You can change downsampling to upsampling in the code and the weights file will load properly!

**Comment by JWFanggit** [comment]
![11](https://github.com/JWFanggit/LOTVS-CAP/assets/83571975/b0f06da7-7671-4315-b56b-be344421a9b7)

**Comment by JWFanggit** [comment]
![265651438-52c52fae-1cf5-4bc9-98ff-c74e72796ef9](https://github.com/JWFanggit/LOTVS-CAP/assets/83571975/4f634bbb-43d7-4675-921f-f22bdd2702ab)

**Comment by BITwtz** [comment]
![image](https://github.com/JWFanggit/LOTVS-CAP/assets/153470867/445c3480-66d8-4446-97f3-80f7e7b83329)
I tried the method you said, but there is still an error as shown in the figure😭

**Comment by JWFanggit** [comment]
Strange😂 Could you please check your code, the symbol（text.textNet）is not in my code.

**Comment by BITwtz** [comment]
![image](https://github.com/JWFanggit/LOTVS-CAP/assets/153470867/df97e570-a32d-4f38-bb83-ea8cd1116943)
I found text.Net in the model.py file. I am not sure if this problem is due to my error in modifying downsampling. I wonder if it is convenient for me to further consult you on wechat.I'm sorry if this is presumptuous.

**Comment by JWFanggit** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JWFanggit/LOTVS-CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月11日(星期一) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JWFanggit/LOTVS-CAP] Some code running issues (Issue #4)





 
image.png (view on web)
 I found text.Net in the model.py file. I am not sure if this problem is due to my error in modifying downsampling. I wonder if it is convenient for me to further consult you on wechat.I'm sorry if this is presumptuous.

**Comment by JWFanggit** [comment]
V：18392533589

**Comment by happytianhao** [comment]
> V：18392533589

Hello, Professor Fang. I encountered the same issue. May I ask for your guidance?
